name: untitled
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-374.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.4.1
  google_sign_in: ^5.0.0
  firebase_core_platform_interface: 4.5.1
  image_picker_web: any
  firebase_storage: ^10.3.2
  firebase_storage_web: any
  path_provider: ^2.0.11
  video_player_web: ^2.0.12
  video_player: ^2.4.9
  cloud_firestore: any
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.1.3+1

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/images/CliPPY.png'
  fullscreen: true

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/